import { Router, type Request, type Response } from "express";
import { z } from "zod";
import { connectMongo } from "./config/db";
import { User, CropAnalysis, Recommendation, GalleryItem, Alert, ContactMessage, PilotApplication } from "./models";
import { optionalAuth, requireAuth, type AuthRequest } from "./middleware/auth";
import { clearTokenCookie, hashPassword, setTokenCookie, signToken, verifyPassword } from "./utils/auth";
import { asyncRoute, errorMessage, saveImage, serialize } from "./utils/http";
import { analyzeCrop } from "../services/plantHealthService";

const router = Router();
const email = z.string().trim().toLowerCase().email().max(320);
const optionalText = (max: number) => z.string().trim().max(max).optional();
const authRegister = z.object({ name: z.string().trim().min(2).max(160), email, password: z.string().min(8).max(128), confirmPassword: z.string() });
const authLogin = z.object({ email, password: z.string().min(1).max(128) });

router.get("/health", (_req, res) => res.json({ ok: true, database: process.env.MONGODB_URI ? "configured" : "missing" }));
router.get("/auth/me", optionalAuth, (req: AuthRequest, res) => res.json(req.user ? serialize(req.user) : null));
router.post("/auth/register", asyncRoute(async (req, res) => { const input = authRegister.parse(req.body); if (input.password !== input.confirmPassword) return res.status(400).json({ message: "Passwords do not match." }); await connectMongo(); if (await User.exists({ email: input.email })) return res.status(409).json({ message: "An account with this email already exists." }); const user = await User.create({ name: input.name, email: input.email, passwordHash: await hashPassword(input.password), loginMethod: "password", lastSignedIn: new Date() }); setTokenCookie(res, signToken(String(user._id))); res.status(201).json(serialize(user)); }));
router.post("/auth/login", asyncRoute(async (req, res) => { const input = authLogin.parse(req.body); await connectMongo(); const user = await User.findOne({ email: input.email }).select("+passwordHash"); if (!user || !(await verifyPassword(input.password, user.passwordHash))) return res.status(401).json({ message: "Email or password is incorrect." }); user.lastSignedIn = new Date(); await user.save(); setTokenCookie(res, signToken(String(user._id))); res.json(serialize(user)); }));
router.post("/auth/logout", (_req, res) => { clearTokenCookie(res); res.json({ success: true }); });

router.patch("/profile", requireAuth, asyncRoute(async (req: AuthRequest, res) => { const input = z.object({ name: z.string().trim().min(2).max(160), preferredLanguage: z.enum(["English", "Tamil"]) }).parse(req.body); await connectMongo(); const user = await User.findByIdAndUpdate(req.user._id, input, { new: true }).select("-passwordHash"); res.json(serialize(user)); }));
router.get("/profile", requireAuth, (_req: AuthRequest, res) => res.json(serialize(_req.user)));

router.post("/analysis", requireAuth, asyncRoute(async (req: AuthRequest, res) => { const input = z.object({ crop: optionalText(80), location: optionalText(240), soilType: optionalText(80), growthStage: optionalText(100), plantingDate: optionalText(32), currentSymptoms: optionalText(1200), previousTreatment: optionalText(1200), imageData: z.string().min(20) }).parse(req.body); const uploaded = await saveImage(String(req.user._id), "analyses/crop", input.imageData); const result = await analyzeCrop(input.imageData, input); const data = { user: req.user._id, cropType: result.crop, location: input.location || null, soilType: input.soilType || "Not provided", growthStage: input.growthStage || null, plantingDate: input.plantingDate || "Not provided", currentSymptoms: input.currentSymptoms || null, previousTreatment: input.previousTreatment || null, imageUrl: uploaded.url, imageKey: uploaded.key, healthStatus: result.healthStatus, confidence: result.confidence, detectedCondition: result.detectedCondition, possibleIssue: result.possibleIssue, severity: result.severity, immediateAction: result.immediateAction, wateringAdvice: result.wateringAdvice, soilGuidance: result.soilGuidance, pestDiseaseManagement: result.pestDiseaseManagement, preventiveMeasures: result.preventiveMeasures, sustainableFarming: result.sustainableFarming, recommendation: result.recommendation, providerModel: result.providerModel || null, mode: result.mode === "demo" ? "fallback" : result.mode }; const analysis = await CropAnalysis.create(data); await Recommendation.create({ ...data, analysis: analysis._id }); res.status(201).json({ ...serialize(analysis), ...result, id: String(analysis._id), cropType: result.crop, imageUrl: uploaded.url, soilType: data.soilType, plantingDate: data.plantingDate, location: data.location || "Not provided", growthStage: data.growthStage || "Not provided", currentSymptoms: data.currentSymptoms || "Not provided", previousTreatment: data.previousTreatment || "Not provided" }); }));
router.get("/analysis/history", requireAuth, asyncRoute(async (req: AuthRequest, res) => { await connectMongo(); const rows = await CropAnalysis.find({ user: req.user._id }).sort({ createdAt: -1 }); res.json(rows.map(serialize)); }));
router.get("/analysis/:id", requireAuth, asyncRoute(async (req: AuthRequest, res) => { await connectMongo(); const row = await CropAnalysis.findOne({ _id: req.params.id, user: req.user._id }); if (!row) return res.status(404).json({ message: "Analysis not found." }); res.json(serialize(row)); }));
router.get("/recommendations", requireAuth, asyncRoute(async (req: AuthRequest, res) => { await connectMongo(); const rows = await Recommendation.find({ user: req.user._id }).sort({ createdAt: -1 }); res.json(rows.map(serialize)); }));

router.get("/gallery", requireAuth, asyncRoute(async (req: AuthRequest, res) => { await connectMongo(); const search = String(req.query.search || "").trim(); const category = String(req.query.category || "").trim(); const filter: any = { user: req.user._id }; if (category && category !== "all") filter.category = category; if (search) filter.$or = [{ cropName: { $regex: search, $options: "i" } }, { description: { $regex: search, $options: "i" } }]; const rows = await GalleryItem.find(filter).sort({ createdAt: -1 }); res.json(rows.map(serialize)); }));
router.post("/gallery", requireAuth, asyncRoute(async (req: AuthRequest, res) => { const input = z.object({ cropName: z.string().trim().min(1).max(120), category: z.enum(["Vegetables", "Fruits", "Cereals", "Flowers", "Other"]), description: z.string().trim().max(500).optional(), imageData: z.string().min(20) }).parse(req.body); const uploaded = await saveImage(String(req.user._id), "gallery/item", input.imageData); await connectMongo(); const item = await GalleryItem.create({ user: req.user._id, imageUrl: uploaded.url, imageKey: uploaded.key, cropName: input.cropName, category: input.category, description: input.description || null }); res.status(201).json(serialize(item)); }));
router.delete("/gallery/:id", requireAuth, asyncRoute(async (req: AuthRequest, res) => { await connectMongo(); const deleted = await GalleryItem.findOneAndDelete({ _id: req.params.id, user: req.user._id }); if (!deleted) return res.status(404).json({ message: "Gallery item not found or not owned by you." }); res.json({ success: true }); }));
router.get("/alerts", requireAuth, asyncRoute(async (req: AuthRequest, res) => { await connectMongo(); const rows = await Alert.find({ user: req.user._id }).sort({ createdAt: -1 }); res.json(rows.map(serialize)); }));
router.post("/contact", asyncRoute(async (req, res) => { const input = z.object({ name: z.string().trim().min(2).max(160), email, phone: optionalText(48), subject: z.string().trim().min(2).max(160), category: z.string().trim().min(1).max(48), message: z.string().trim().min(20).max(5000) }).parse(req.body); await connectMongo(); await ContactMessage.create(input); res.status(201).json({ success: true }); }));
router.post("/intake/pilot", asyncRoute(async (req, res) => { const input = z.object({ name: z.string().min(2), phone: z.string().min(6), email, location: z.string().min(2), farmSize: z.string().min(1), crop: z.string().min(1), language: z.string().min(1), consent: z.boolean() }).parse(req.body); if (!input.consent) return res.status(400).json({ message: "Consent is required." }); await connectMongo(); await PilotApplication.create({ ...input, preferredLanguage: input.language }); res.status(201).json({ success: true }); }));

router.use((error: any, _req: Request, res: Response, _next: Function) => { const status = Number(error?.status) || (error?.name === "ZodError" ? 400 : 500); if (status >= 500) console.error("[MERN API]", error); res.status(status).json({ message: status >= 500 ? "The server could not complete that request." : errorMessage(error) }); });
export const mernApi = router;
