import DashboardLayout from "@/components/DashboardLayout";
import { api } from "@/lib/api";
import { FileImage, Filter, ImagePlus, Loader2, Search, Trash2, UploadCloud, X } from "lucide-react";
import { ChangeEvent, DragEvent, FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";

const categories = ["all", "Vegetables", "Fruits", "Cereals", "Flowers", "Other"] as const;

export default function Gallery() {
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState<string>("all");
  const [showForm, setShowForm] = useState(false);
  const input = useMemo(() => ({ search: search || undefined, category: category === "all" ? undefined : category }), [search, category]);
  const query = api.gallery.list.useQuery(input);
  const utils = api.useUtils();
  const remove = api.gallery.remove.useMutation({ onSuccess: () => { toast.success("Gallery item removed."); utils.gallery.list.invalidate(); } });
  const items = query.data ?? [];
  return <DashboardLayout><div className="mx-auto max-w-6xl space-y-7 p-2 sm:p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Your visual field notes</p><h1 className="mt-2 font-display text-4xl font-semibold tracking-tight text-[#1d4d31]">Gallery</h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#718071]">Keep a private, searchable record of your crops. Only images you upload are shown here.</p></div><button onClick={() => setShowForm((value) => !value)} className="w-fit rounded-xl bg-[#1d6a3b] px-4 py-3 text-sm font-bold text-white">{showForm ? <><X className="mr-2 inline h-4 w-4" /> Close</> : <><ImagePlus className="mr-2 inline h-4 w-4" /> Add gallery image</>}</button></div>{showForm && <GalleryForm onDone={() => { setShowForm(false); utils.gallery.list.invalidate(); }} />}
    <div className="flex flex-col gap-3 rounded-[1.5rem] border border-[#dce7d9] bg-white p-4 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-[#819182]" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search your crops or descriptions" className="h-10 w-full rounded-xl border border-[#d6e2d3] pl-9 pr-3 text-sm outline-none focus:border-[#4a965e]" /></label><label className="flex items-center gap-2 text-sm font-semibold text-[#527058]"><Filter className="h-4 w-4" /><select value={category} onChange={(e) => setCategory(e.target.value)} className="h-10 rounded-xl border border-[#d6e2d3] bg-white px-3 outline-none">{categories.map((value) => <option key={value} value={value}>{value === "all" ? "All categories" : value}</option>)}</select></label></div>
    {query.isLoading ? <Loading /> : query.isError ? <State title="Gallery unavailable" text="We couldn't load your gallery. Please refresh and try again." /> : items.length === 0 ? <State title={search || category !== "all" ? "No matching images" : "Your gallery is empty"} text={search || category !== "all" ? "Try a different search or category." : "Upload a crop photo to start building your private field record."} /> : <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <article key={item.id} className="overflow-hidden rounded-[1.5rem] border border-[#dce7d9] bg-white"><div className="relative aspect-[4/3] bg-[#eaf2e5]"><img src={item.imageUrl} alt={`${item.cropName} gallery upload`} className="h-full w-full object-cover" loading="lazy" /><button onClick={() => { if (window.confirm("Remove this gallery image?")) remove.mutate({ id: item.id }); }} className="absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-xl bg-white/90 text-[#a64f42] shadow-sm" aria-label={`Delete ${item.cropName} image`}><Trash2 className="h-4 w-4" /></button></div><div className="p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-display text-xl font-semibold text-[#234d31]">{item.cropName}</h2><span className="rounded-full bg-[#e6f2e0] px-2.5 py-1 text-[11px] font-bold text-[#39814f]">{item.category}</span></div>{item.description && <p className="mt-3 text-sm leading-6 text-[#718071]">{item.description}</p>}<p className="mt-4 text-xs text-[#97a497]">Uploaded {new Date(item.createdAt).toLocaleDateString()}</p></div></article>)}</div>}</div></DashboardLayout>;
}

function GalleryForm({ onDone }: { onDone: () => void }) {
  const [form, setForm] = useState({ cropName: "", category: "Vegetables" as (typeof categories)[number], description: "" });
  const [image, setImage] = useState("");
  const [error, setError] = useState("");
  const create = api.gallery.create.useMutation({ onSuccess: () => { toast.success("Image saved to your gallery."); onDone(); } });
  const handleFile = (file?: File) => { if (!file) return; if (!["image/jpeg", "image/png", "image/webp"].includes(file.type)) return setError("Please upload JPG, PNG, or WEBP."); if (file.size > 6 * 1024 * 1024) return setError("Image size must be less than 6 MB."); setError(""); const reader = new FileReader(); reader.onload = () => setImage(String(reader.result)); reader.readAsDataURL(file); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!image) return setError("Choose an image before saving."); create.mutate({ cropName: form.cropName, category: form.category as "Vegetables" | "Fruits" | "Cereals" | "Flowers" | "Other", description: form.description || undefined, imageData: image }); };
  return <form onSubmit={submit} className="rounded-[1.5rem] border border-[#cfe0c9] bg-[#f3f8ed] p-5 sm:p-7"><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="grid content-start gap-4"><label className="grid gap-2 text-sm font-bold text-[#49634f]">Crop or plant name<input required value={form.cropName} onChange={(e) => setForm({ ...form, cropName: e.target.value })} className="h-11 rounded-xl border border-[#cddccc] bg-white px-3 font-normal" placeholder="e.g. Tomato" /></label><label className="grid gap-2 text-sm font-bold text-[#49634f]">Category<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value as (typeof categories)[number] })} className="h-11 rounded-xl border border-[#cddccc] bg-white px-3 font-normal">{categories.slice(1).map((value) => <option key={value}>{value}</option>)}</select></label><label className="grid gap-2 text-sm font-bold text-[#49634f]">Description <textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="min-h-24 rounded-xl border border-[#cddccc] bg-white px-3 py-2 font-normal" placeholder="What would you like to remember about this plant?" /></label></div><div><label onDragOver={(e) => e.preventDefault()} onDrop={(e: DragEvent<HTMLLabelElement>) => { e.preventDefault(); handleFile(e.dataTransfer.files[0]); }} className="flex min-h-64 cursor-pointer flex-col items-center justify-center overflow-hidden rounded-2xl border-2 border-dashed border-[#aacaa8] bg-white text-center">{image ? <img src={image} alt="Gallery preview" className="h-64 w-full object-cover" /> : <><UploadCloud className="h-9 w-9 text-[#4b925b]" /><p className="mt-4 font-semibold text-[#345b3f]">Drop an image here or browse</p><p className="mt-2 text-xs text-[#819182]">JPG, PNG, WEBP · up to 6 MB</p></>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e: ChangeEvent<HTMLInputElement>) => handleFile(e.target.files?.[0])} className="hidden" /></label>{error && <p role="alert" className="mt-3 text-sm font-semibold text-[#a64f42]">{error}</p>}<button disabled={create.isPending} className="mt-4 rounded-xl bg-[#1d6a3b] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{create.isPending ? <><Loader2 className="mr-2 inline h-4 w-4 animate-spin" /> Saving…</> : "Save image"}</button></div></div></form>;
}

function Loading() { return <div className="grid min-h-64 place-items-center rounded-[1.5rem] border border-[#dce7d9] bg-white text-sm text-[#718071]"><Loader2 className="mr-2 inline h-4 w-4 animate-spin" /> Loading gallery…</div>; }
function State({ title, text }: { title: string; text: string }) { return <div className="grid min-h-64 place-items-center rounded-[1.5rem] border border-dashed border-[#cbdcc9] bg-[#f4f8ef] p-8 text-center"><div><FileImage className="mx-auto h-10 w-10 text-[#609267]" /><h2 className="mt-4 font-display text-xl font-semibold text-[#234d31]">{title}</h2><p className="mt-2 text-sm text-[#718071]">{text}</p></div></div>; }
