import PublicLayout from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Loader2, Mail, Sprout } from "lucide-react";
import { FormEvent, useState } from "react";

export default function About() {
  return <PublicLayout><main><section className="container grid gap-12 py-20 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:py-28"><div><p className="eyebrow">About the project</p><h1 className="section-title mt-4 max-w-3xl">Practical crop intelligence for the people who work closest to the soil.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#637367]">Chennai AgroSmart AI is an AI-powered agriculture platform designed to help farmers and students analyze crop photos, understand possible plant-health signals, and keep useful field records.</p></div><div className="rounded-[2rem] bg-[#18432e] p-8 text-white shadow-[0_24px_60px_rgba(29,81,47,.18)]"><Sprout className="h-9 w-9 text-[#c5e6a4]" /><h2 className="mt-8 font-display text-2xl font-semibold">Designed for clarity</h2><p className="mt-3 leading-7 text-[#c6dcc7]">The product focuses on one useful loop: upload a photo, understand the result, and decide on a sensible next step.</p></div></section><section className="border-y border-[#dbe5d7] bg-white py-20"><div className="container grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><InfoCard title="The problem" text="Crop issues are often noticed before a farmer has easy access to a clear, contextual explanation." /><InfoCard title="The solution" text="A calm, mobile-friendly workflow brings image analysis, simple recommendations, and history together." /><InfoCard title="The AI component" text="The service layer is modular. It can use a validated vision provider while keeping uncertainty visible to the user." /><InfoCard title="Sustainability" text="Recommendations emphasize checking soil moisture, reducing unnecessary inputs, and choosing practical preventative steps." /><InfoCard title="Target users" text="Small farmers, agricultural students, community pilots, and anyone learning to observe crop health." /><InfoCard title="Future scope" text="Tamil guidance, voice support, weather context, field records, and improved model validation are planned extensions." /></div></section></main></PublicLayout>;
}

function InfoCard({ title, text }: { title: string; text: string }) { return <article className="rounded-[1.5rem] border border-[#dce7d9] bg-[#f8faf5] p-6"><h2 className="font-display text-xl font-semibold text-[#234d31]">{title}</h2><p className="mt-3 text-sm leading-6 text-[#718071]">{text}</p></article>; }

export function Contact() {
  const send = trpc.intake.submitContact.useMutation();
  const [sent, setSent] = useState(false);
  const [error, setError] = useState("");
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); try { await send.mutateAsync({ name: String(data.get("name")), email: String(data.get("email")), subject: String(data.get("subject")), category: String(data.get("category")), message: String(data.get("message")) }); setSent(true); event.currentTarget.reset(); } catch (err) { setError(err instanceof Error ? err.message : "We couldn't send your message."); } };
  return <PublicLayout><main className="container grid gap-12 py-20 lg:grid-cols-[.8fr_1.2fr] lg:py-28"><div><p className="eyebrow">Contact</p><h1 className="section-title mt-4">Tell us what would make the field workflow more useful.</h1><p className="mt-6 leading-7 text-[#68786d]">Questions, pilot ideas, accessibility feedback, or crop-analysis suggestions are welcome. Messages are recorded for the project team; email delivery is not claimed unless a mail service is configured.</p><div className="mt-8 flex items-center gap-3 text-sm font-semibold text-[#45624c]"><Mail className="h-5 w-5 text-[#4b925b]" /> Stored securely in the project database</div></div><form onSubmit={submit} className="rounded-[2rem] border border-[#dce7d9] bg-white p-6 shadow-[0_18px_50px_rgba(37,75,49,.08)] sm:p-9"><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold text-[#49634f]">Name<input required name="name" minLength={2} className="h-11 rounded-xl border border-[#cddccc] px-3 font-normal" /></label><label className="grid gap-2 text-sm font-bold text-[#49634f]">Email<input required type="email" name="email" className="h-11 rounded-xl border border-[#cddccc] px-3 font-normal" /></label></div><label className="mt-4 grid gap-2 text-sm font-bold text-[#49634f]">Subject<input required name="subject" minLength={2} className="h-11 rounded-xl border border-[#cddccc] px-3 font-normal" /></label><label className="mt-4 grid gap-2 text-sm font-bold text-[#49634f]">Topic<select name="category" className="h-11 rounded-xl border border-[#cddccc] bg-white px-3 font-normal"><option>Product feedback</option><option>Pilot enquiry</option><option>Accessibility</option><option>Other</option></select></label><label className="mt-4 grid gap-2 text-sm font-bold text-[#49634f]">Message<textarea required name="message" minLength={20} className="min-h-36 rounded-xl border border-[#cddccc] px-3 py-2 font-normal" placeholder="Please share at least a little context so we can help." /></label>{sent && <p role="status" className="mt-4 rounded-xl bg-[#e8f5e4] px-3 py-2 text-sm font-semibold text-[#337248]"><CheckCircle2 className="mr-2 inline h-4 w-4" /> Message recorded successfully.</p>}{error && <p role="alert" className="mt-4 rounded-xl bg-[#fff0ec] px-3 py-2 text-sm font-semibold text-[#a64f42]">{error}</p>}<button disabled={send.isPending} className="mt-5 rounded-xl bg-[#1d6a3b] px-5 py-3.5 text-sm font-bold text-white disabled:opacity-60">{send.isPending ? <><Loader2 className="mr-2 inline h-4 w-4 animate-spin" /> Sending…</> : "Send message"}</button></form></main></PublicLayout>;
}
